module.exports = [ 
    { 
       "id":14131,
       "url":"https:\/\/yts.lt\/movie\/honey-we-shrunk-ourselves-1997",
       "imdb_code":"tt0119310",
       "title":"Honey, We Shrunk Ourselves!",
       "title_english":"Honey, We Shrunk Ourselves!",
       "title_long":"Honey, We Shrunk Ourselves! (1997)",
       "slug":"honey-we-shrunk-ourselves-1997",
       "year":1997,
       "rating":4.9,
       "runtime":74,
       "genres":[ 
          "Action",
          "Adventure",
          "Comedy",
          "Family",
          "Sci-Fi"
       ],
       "summary":"Wayne Szalinzki, a wacky, absent-minded inventor, is back again but only this time he decides to use his infamous shrink machine just one more time. His wife Diane asks him to get rid of the \"Tiki Man\" a large tiki sculpture. Wayne refuses to get rid of it so he decides to restart the shrink ray and reduces the Tiki Man to pocket-size. However, after Wayne shrinks the Tiki Man the machine is accidentally activated and Wayne ends up shrinking himself and his brother Gordon. Meanwhile, when Gordon's wife Patty and Diane were going on a vacation they went back to the house when Patty suddenly realizes she forgot Mitch's medicine for his potassium deficiency. When they were about to leave, they decide to sneak into the attic and surprise the men, but the shrink ray is activated once again, and the ladies are shrunk as well. So the team must be very brave of disgusting household insects the size of dinosaurs and more in their biggest adventure to get their children's attention.",
       "description_full":"Wayne Szalinzki, a wacky, absent-minded inventor, is back again but only this time he decides to use his infamous shrink machine just one more time. His wife Diane asks him to get rid of the \"Tiki Man\" a large tiki sculpture. Wayne refuses to get rid of it so he decides to restart the shrink ray and reduces the Tiki Man to pocket-size. However, after Wayne shrinks the Tiki Man the machine is accidentally activated and Wayne ends up shrinking himself and his brother Gordon. Meanwhile, when Gordon's wife Patty and Diane were going on a vacation they went back to the house when Patty suddenly realizes she forgot Mitch's medicine for his potassium deficiency. When they were about to leave, they decide to sneak into the attic and surprise the men, but the shrink ray is activated once again, and the ladies are shrunk as well. So the team must be very brave of disgusting household insects the size of dinosaurs and more in their biggest adventure to get their children's attention.",
       "synopsis":"Wayne Szalinzki, a wacky, absent-minded inventor, is back again but only this time he decides to use his infamous shrink machine just one more time. His wife Diane asks him to get rid of the \"Tiki Man\" a large tiki sculpture. Wayne refuses to get rid of it so he decides to restart the shrink ray and reduces the Tiki Man to pocket-size. However, after Wayne shrinks the Tiki Man the machine is accidentally activated and Wayne ends up shrinking himself and his brother Gordon. Meanwhile, when Gordon's wife Patty and Diane were going on a vacation they went back to the house when Patty suddenly realizes she forgot Mitch's medicine for his potassium deficiency. When they were about to leave, they decide to sneak into the attic and surprise the men, but the shrink ray is activated once again, and the ladies are shrunk as well. So the team must be very brave of disgusting household insects the size of dinosaurs and more in their biggest adventure to get their children's attention.",
       "yt_trailer_code":"ilSd567cYso",
       "language":"English",
       "mpa_rating":"PG",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/honey_we_shrunk_ourselves_1997\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/honey_we_shrunk_ourselves_1997\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/honey_we_shrunk_ourselves_1997\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/honey_we_shrunk_ourselves_1997\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/honey_we_shrunk_ourselves_1997\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/ABE14EAF848C855337E1BD630B509E7B56977E8C",
             "hash":"ABE14EAF848C855337E1BD630B509E7B56977E8C",
             "quality":"720p",
             "type":"web",
             "seeds":0,
             "peers":0,
             "size":"629.53 MB",
             "size_bytes":660110049,
             "date_uploaded":"2019-11-04 00:51:59",
             "date_uploaded_unix":1572825119
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/399B9735D367F799BEB2D605BDD1F3DBBD9DA84B",
             "hash":"399B9735D367F799BEB2D605BDD1F3DBBD9DA84B",
             "quality":"1080p",
             "type":"web",
             "seeds":0,
             "peers":0,
             "size":"1.12 GB",
             "size_bytes":1202590843,
             "date_uploaded":"2019-11-04 02:07:31",
             "date_uploaded_unix":1572829651
          }
       ],
       "date_uploaded":"2019-11-04 00:51:59",
       "date_uploaded_unix":1572825119
    },
    { 
       "id":14130,
       "url":"https:\/\/yts.lt\/movie\/shelley-2016",
       "imdb_code":"tt5013688",
       "title":"Shelley",
       "title_english":"Shelley",
       "title_long":"Shelley (2016)",
       "slug":"shelley-2016",
       "year":2016,
       "rating":5.2,
       "runtime":92,
       "genres":[ 
          "Drama",
          "Horror"
       ],
       "summary":"Louise and Kasper, a Danish couple, live in an isolated villa in the middle of the forest away from modern life, technology and even electricity. Louise's biggest dream is to become a mother but she is unable to have children. She finally decides, out of desperation, to seal a pact with her Romanian maid, Elena. Elena accepts to bear Louise's child as a surrogate mother in exchange for a large amount of money. The life growing inside of her is taking shape too fast, affecting the lives of everyone like an evil force. Paranoia and horror set in around the inevitable birth...",
       "description_full":"Louise and Kasper, a Danish couple, live in an isolated villa in the middle of the forest away from modern life, technology and even electricity. Louise's biggest dream is to become a mother but she is unable to have children. She finally decides, out of desperation, to seal a pact with her Romanian maid, Elena. Elena accepts to bear Louise's child as a surrogate mother in exchange for a large amount of money. The life growing inside of her is taking shape too fast, affecting the lives of everyone like an evil force. Paranoia and horror set in around the inevitable birth...",
       "synopsis":"Louise and Kasper, a Danish couple, live in an isolated villa in the middle of the forest away from modern life, technology and even electricity. Louise's biggest dream is to become a mother but she is unable to have children. She finally decides, out of desperation, to seal a pact with her Romanian maid, Elena. Elena accepts to bear Louise's child as a surrogate mother in exchange for a large amount of money. The life growing inside of her is taking shape too fast, affecting the lives of everyone like an evil force. Paranoia and horror set in around the inevitable birth...",
       "yt_trailer_code":"OTc5RSuQkxQ",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/shelley_2016\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/shelley_2016\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/shelley_2016\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/shelley_2016\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/shelley_2016\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/AA8060B5FC632349DAFB4A08D30D2E4690E5CF62",
             "hash":"AA8060B5FC632349DAFB4A08D30D2E4690E5CF62",
             "quality":"720p",
             "type":"bluray",
             "seeds":0,
             "peers":0,
             "size":"811.11 MB",
             "size_bytes":850510479,
             "date_uploaded":"2019-11-03 20:31:44",
             "date_uploaded_unix":1572809504
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/0C9E36A17E5829AF586CDA6B72E254BCCDED63C3",
             "hash":"0C9E36A17E5829AF586CDA6B72E254BCCDED63C3",
             "quality":"1080p",
             "type":"bluray",
             "seeds":0,
             "peers":0,
             "size":"1.44 GB",
             "size_bytes":1546188227,
             "date_uploaded":"2019-11-03 22:22:14",
             "date_uploaded_unix":1572816134
          }
       ],
       "date_uploaded":"2019-11-03 20:31:44",
       "date_uploaded_unix":1572809504
    },
    { 
       "id":14129,
       "url":"https:\/\/yts.lt\/movie\/oil-in-the-blood-2019",
       "imdb_code":"tt8710502",
       "title":"Oil in the Blood",
       "title_english":"Oil in the Blood",
       "title_long":"Oil in the Blood (2019)",
       "slug":"oil-in-the-blood-2019",
       "year":2019,
       "rating":6,
       "runtime":130,
       "genres":[ 
          "Documentary"
       ],
       "summary":"'Oil in the Blood' is a documentary feature film on the contemporary custom motorcycle culture. It's not a film about motorcycles, it's a film about motorcycle people.The philosophy of individualism is embedded in motorcycling. The desire to be different, unique, is at the root of the motorcyclist's imagination. Modifying, customising, changing bikes is at the very heart of the biker.The new wave custom scene as it is today, is a thriving subculture sitting on the edge of the mainstream motorcycle world, where individuals and groups of friends are busily chopping and building bikes in their sheds and kitchens; where single- proprietor micro- businesses are creating bespoke motorcycles for fuel hungry customers. Old forgotten motorcycles and models are being brought back to life - unfashionable, ugly ducklings turned into often preening peacocks. Old skills that were once disappearing are being learnt and mastered by a new generation, where the pride comes from graft and not purchasing...",
       "description_full":"'Oil in the Blood' is a documentary feature film on the contemporary custom motorcycle culture. It's not a film about motorcycles, it's a film about motorcycle people.The philosophy of individualism is embedded in motorcycling. The desire to be different, unique, is at the root of the motorcyclist's imagination. Modifying, customising, changing bikes is at the very heart of the biker.The new wave custom scene as it is today, is a thriving subculture sitting on the edge of the mainstream motorcycle world, where individuals and groups of friends are busily chopping and building bikes in their sheds and kitchens; where single- proprietor micro- businesses are creating bespoke motorcycles for fuel hungry customers. Old forgotten motorcycles and models are being brought back to life - unfashionable, ugly ducklings turned into often preening peacocks. Old skills that were once disappearing are being learnt and mastered by a new generation, where the pride comes from graft and not purchasing...",
       "synopsis":"'Oil in the Blood' is a documentary feature film on the contemporary custom motorcycle culture. It's not a film about motorcycles, it's a film about motorcycle people.The philosophy of individualism is embedded in motorcycling. The desire to be different, unique, is at the root of the motorcyclist's imagination. Modifying, customising, changing bikes is at the very heart of the biker.The new wave custom scene as it is today, is a thriving subculture sitting on the edge of the mainstream motorcycle world, where individuals and groups of friends are busily chopping and building bikes in their sheds and kitchens; where single- proprietor micro- businesses are creating bespoke motorcycles for fuel hungry customers. Old forgotten motorcycles and models are being brought back to life - unfashionable, ugly ducklings turned into often preening peacocks. Old skills that were once disappearing are being learnt and mastered by a new generation, where the pride comes from graft and not purchasing...",
       "yt_trailer_code":"fYTK8Yt0MCs",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/oil_in_the_blood_2019\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/oil_in_the_blood_2019\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/oil_in_the_blood_2019\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/oil_in_the_blood_2019\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/oil_in_the_blood_2019\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/92E36F5289E0A292245C28AC063DEAB8E31385BB",
             "hash":"92E36F5289E0A292245C28AC063DEAB8E31385BB",
             "quality":"720p",
             "type":"bluray",
             "seeds":178,
             "peers":84,
             "size":"1.08 GB",
             "size_bytes":1159641170,
             "date_uploaded":"2019-11-03 16:08:21",
             "date_uploaded_unix":1572793701
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/408CB0BD21DAF09CDEA06C0F94BEE2465E6C9CB5",
             "hash":"408CB0BD21DAF09CDEA06C0F94BEE2465E6C9CB5",
             "quality":"1080p",
             "type":"bluray",
             "seeds":104,
             "peers":111,
             "size":"1.95 GB",
             "size_bytes":2093796557,
             "date_uploaded":"2019-11-03 18:21:14",
             "date_uploaded_unix":1572801674
          }
       ],
       "date_uploaded":"2019-11-03 16:08:21",
       "date_uploaded_unix":1572793701
    },
    { 
       "id":14128,
       "url":"https:\/\/yts.lt\/movie\/tuck-everlasting-2002",
       "imdb_code":"tt0283084",
       "title":"Tuck Everlasting",
       "title_english":"Tuck Everlasting",
       "title_long":"Tuck Everlasting (2002)",
       "slug":"tuck-everlasting-2002",
       "year":2002,
       "rating":6.6,
       "runtime":90,
       "genres":[ 
          "Drama",
          "Family",
          "Fantasy",
          "Romance"
       ],
       "summary":"Winnie Foster has everything a young woman could desire. She comes from a well-bred, wealthy, and respected family. She dresses in the finest clothes and is afforded every opportunity to refine herself. But Winnie finds that the heat of summer is not nearly as stifling as her gilded cage. She longs for freedom, for adventure. She escapes one morning to explore the woods surrounding her family's home, and encounters the Tucks, a close-knit family with a mysterious past that begs the question: If you could live forever, would you? And just when Winnie believes she has answered that question for herself, a mysterious man looking to profit from the source of the Tuck's immortality that will have her question her life, her desires, and what is the right thing to do. And in the end, learns, that death is not what is to be feared, but an unlived life.",
       "description_full":"Winnie Foster has everything a young woman could desire. She comes from a well-bred, wealthy, and respected family. She dresses in the finest clothes and is afforded every opportunity to refine herself. But Winnie finds that the heat of summer is not nearly as stifling as her gilded cage. She longs for freedom, for adventure. She escapes one morning to explore the woods surrounding her family's home, and encounters the Tucks, a close-knit family with a mysterious past that begs the question: If you could live forever, would you? And just when Winnie believes she has answered that question for herself, a mysterious man looking to profit from the source of the Tuck's immortality that will have her question her life, her desires, and what is the right thing to do. And in the end, learns, that death is not what is to be feared, but an unlived life.",
       "synopsis":"Winnie Foster has everything a young woman could desire. She comes from a well-bred, wealthy, and respected family. She dresses in the finest clothes and is afforded every opportunity to refine herself. But Winnie finds that the heat of summer is not nearly as stifling as her gilded cage. She longs for freedom, for adventure. She escapes one morning to explore the woods surrounding her family's home, and encounters the Tucks, a close-knit family with a mysterious past that begs the question: If you could live forever, would you? And just when Winnie believes she has answered that question for herself, a mysterious man looking to profit from the source of the Tuck's immortality that will have her question her life, her desires, and what is the right thing to do. And in the end, learns, that death is not what is to be feared, but an unlived life.",
       "yt_trailer_code":"rXbbAbDvifw",
       "language":"English",
       "mpa_rating":"PG",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/tuck_everlasting_2002\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/tuck_everlasting_2002\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/tuck_everlasting_2002\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/tuck_everlasting_2002\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/tuck_everlasting_2002\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/AD52109C3B656E37CBB28279C0C0333001B38570",
             "hash":"AD52109C3B656E37CBB28279C0C0333001B38570",
             "quality":"720p",
             "type":"web",
             "seeds":230,
             "peers":122,
             "size":"800.92 MB",
             "size_bytes":839825490,
             "date_uploaded":"2019-11-03 13:35:30",
             "date_uploaded_unix":1572784530
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/F27CB82B26F723F27E3F176204A399B051E60EF0",
             "hash":"F27CB82B26F723F27E3F176204A399B051E60EF0",
             "quality":"1080p",
             "type":"web",
             "seeds":248,
             "peers":111,
             "size":"1.41 GB",
             "size_bytes":1513975972,
             "date_uploaded":"2019-11-03 14:58:17",
             "date_uploaded_unix":1572789497
          }
       ],
       "date_uploaded":"2019-11-03 13:35:30",
       "date_uploaded_unix":1572784530
    },
    { 
       "id":14127,
       "url":"https:\/\/yts.lt\/movie\/draug-2018",
       "imdb_code":"tt6014434",
       "title":"Draug",
       "title_english":"Draug",
       "title_long":"Draug (2018)",
       "slug":"draug-2018",
       "year":2018,
       "rating":4.7,
       "runtime":0,
       "genres":[ 
          "Horror"
       ],
       "summary":"In the 11th century a missionary goes missing somewhere in the huge forests bordering the northern parts of Sweden. Among the rescue party chosen to find him is Nanna, a young woman on her first real mission and her first return to the part of the country where she was born. But what they will find deep inside those woods is something else entirely. Something dark. Something ancient. Something evil.",
       "description_full":"In the 11th century a missionary goes missing somewhere in the huge forests bordering the northern parts of Sweden. Among the rescue party chosen to find him is Nanna, a young woman on her first real mission and her first return to the part of the country where she was born. But what they will find deep inside those woods is something else entirely. Something dark. Something ancient. Something evil.",
       "synopsis":"In the 11th century a missionary goes missing somewhere in the huge forests bordering the northern parts of Sweden. Among the rescue party chosen to find him is Nanna, a young woman on her first real mission and her first return to the part of the country where she was born. But what they will find deep inside those woods is something else entirely. Something dark. Something ancient. Something evil.",
       "yt_trailer_code":"",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/draug_2018\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/draug_2018\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/draug_2018\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/draug_2018\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/draug_2018\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/1ABD9FA7940987F1D82D77B1E03E1A01C41CFBB1",
             "hash":"1ABD9FA7940987F1D82D77B1E03E1A01C41CFBB1",
             "quality":"720p",
             "type":"bluray",
             "seeds":261,
             "peers":165,
             "size":"782.89 MB",
             "size_bytes":820919665,
             "date_uploaded":"2019-11-03 11:37:00",
             "date_uploaded_unix":1572777420
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/13C2AACE9E945130463BD7E0FCF5DF22B4C61262",
             "hash":"13C2AACE9E945130463BD7E0FCF5DF22B4C61262",
             "quality":"1080p",
             "type":"bluray",
             "seeds":244,
             "peers":85,
             "size":"1.37 GB",
             "size_bytes":1471026299,
             "date_uploaded":"2019-11-03 13:08:53",
             "date_uploaded_unix":1572782933
          }
       ],
       "date_uploaded":"2019-11-03 11:37:00",
       "date_uploaded_unix":1572777420
    },
    { 
       "id":14126,
       "url":"https:\/\/yts.lt\/movie\/good-game-2014",
       "imdb_code":"tt2141753",
       "title":"Good Game",
       "title_english":"Good Game",
       "title_long":"Good Game (2014)",
       "slug":"good-game-2014",
       "year":2014,
       "rating":6.6,
       "runtime":73,
       "genres":[ 
          "Biography",
          "Documentary",
          "Sport"
       ],
       "summary":"For a select group of young men, video gaming isn't just a hobby, it's a job. To be a professional gamer, you need a competitive drive, tactical skill, and creativity. With increasingly larger prizes and six figure player salaries, e-sports is on the rise as a career. Good Game follows a new kind of athlete, the StarCraft 2 division of team Evil Geniuses, as they compete around the world to take the top prizes in the biggest tournaments. But between injuries, exhaustion, and egos, those who start at the top might not stay there for long. New superstars are waiting to take the spotlight, and wanting to succeed sometimes just isn't enough.",
       "description_full":"For a select group of young men, video gaming isn't just a hobby, it's a job. To be a professional gamer, you need a competitive drive, tactical skill, and creativity. With increasingly larger prizes and six figure player salaries, e-sports is on the rise as a career. Good Game follows a new kind of athlete, the StarCraft 2 division of team Evil Geniuses, as they compete around the world to take the top prizes in the biggest tournaments. But between injuries, exhaustion, and egos, those who start at the top might not stay there for long. New superstars are waiting to take the spotlight, and wanting to succeed sometimes just isn't enough.",
       "synopsis":"For a select group of young men, video gaming isn't just a hobby, it's a job. To be a professional gamer, you need a competitive drive, tactical skill, and creativity. With increasingly larger prizes and six figure player salaries, e-sports is on the rise as a career. Good Game follows a new kind of athlete, the StarCraft 2 division of team Evil Geniuses, as they compete around the world to take the top prizes in the biggest tournaments. But between injuries, exhaustion, and egos, those who start at the top might not stay there for long. New superstars are waiting to take the spotlight, and wanting to succeed sometimes just isn't enough.",
       "yt_trailer_code":"",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/good_game_2014\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/good_game_2014\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/good_game_2014\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/good_game_2014\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/good_game_2014\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/D09C4D588CED0D57E1C954CBB6E917B3B94475AC",
             "hash":"D09C4D588CED0D57E1C954CBB6E917B3B94475AC",
             "quality":"720p",
             "type":"web",
             "seeds":107,
             "peers":39,
             "size":"634.42 MB",
             "size_bytes":665237586,
             "date_uploaded":"2019-11-03 08:30:46",
             "date_uploaded_unix":1572766246
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/FFDD6F78ED436B39194DF3A3C24E5BC77DB86B1C",
             "hash":"FFDD6F78ED436B39194DF3A3C24E5BC77DB86B1C",
             "quality":"1080p",
             "type":"web",
             "seeds":154,
             "peers":36,
             "size":"1.13 GB",
             "size_bytes":1213328261,
             "date_uploaded":"2019-11-03 09:58:35",
             "date_uploaded_unix":1572771515
          }
       ],
       "date_uploaded":"2019-11-03 08:30:46",
       "date_uploaded_unix":1572766246
    },
    { 
       "id":14125,
       "url":"https:\/\/yts.lt\/movie\/final-episode-1974",
       "imdb_code":"tt0226018",
       "title":"Final Episode",
       "title_english":"Final Episode",
       "title_long":"Final Episode (1974)",
       "slug":"final-episode-1974",
       "year":1974,
       "rating":7.5,
       "runtime":100,
       "genres":[ 
          "Action",
          "Crime",
          "Drama"
       ],
       "summary":"While Hirono is in prison, his rival Takeda turns his own crime organization into a political party, whose two executives stir up new tensions in their thirst for power.",
       "description_full":"While Hirono is in prison, his rival Takeda turns his own crime organization into a political party, whose two executives stir up new tensions in their thirst for power.",
       "synopsis":"While Hirono is in prison, his rival Takeda turns his own crime organization into a political party, whose two executives stir up new tensions in their thirst for power.",
       "yt_trailer_code":"",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/final_episode_1974\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/final_episode_1974\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/final_episode_1974\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/final_episode_1974\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/final_episode_1974\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/4B30BD70CF1C01E8C50611BB8FD94CD8E4408DA3",
             "hash":"4B30BD70CF1C01E8C50611BB8FD94CD8E4408DA3",
             "quality":"720p",
             "type":"bluray",
             "seeds":53,
             "peers":23,
             "size":"841.51 MB",
             "size_bytes":882387190,
             "date_uploaded":"2019-11-03 05:40:42",
             "date_uploaded_unix":1572756042
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/F036D7AAAEDBEDCA69000F9EC24A952C8C29B1F9",
             "hash":"F036D7AAAEDBEDCA69000F9EC24A952C8C29B1F9",
             "quality":"1080p",
             "type":"bluray",
             "seeds":89,
             "peers":32,
             "size":"1.5 GB",
             "size_bytes":1610612736,
             "date_uploaded":"2019-11-03 07:43:58",
             "date_uploaded_unix":1572763438
          }
       ],
       "date_uploaded":"2019-11-03 05:40:42",
       "date_uploaded_unix":1572756042
    },
    { 
       "id":14124,
       "url":"https:\/\/yts.lt\/movie\/prancer-1989",
       "imdb_code":"tt0098115",
       "title":"Prancer",
       "title_english":"Prancer",
       "title_long":"Prancer (1989)",
       "slug":"prancer-1989",
       "year":1989,
       "rating":6.4,
       "runtime":103,
       "genres":[ 
          "Drama",
          "Family",
          "Fantasy"
       ],
       "summary":"Jessica, the daughter of an impoverished farmer, still believes in Santa Claus. So when she comes across a reindeer with an injured leg, it makes perfect sense to her to assume that it is Prancer, who had fallen from a Christmas display in town. She hides him in her barn and feeds him cookies, until she can return him to Santa. Her father finds him and decides to sell him to the butcher, not for venison chops, but as an advertising display.",
       "description_full":"Jessica, the daughter of an impoverished farmer, still believes in Santa Claus. So when she comes across a reindeer with an injured leg, it makes perfect sense to her to assume that it is Prancer, who had fallen from a Christmas display in town. She hides him in her barn and feeds him cookies, until she can return him to Santa. Her father finds him and decides to sell him to the butcher, not for venison chops, but as an advertising display.",
       "synopsis":"Jessica, the daughter of an impoverished farmer, still believes in Santa Claus. So when she comes across a reindeer with an injured leg, it makes perfect sense to her to assume that it is Prancer, who had fallen from a Christmas display in town. She hides him in her barn and feeds him cookies, until she can return him to Santa. Her father finds him and decides to sell him to the butcher, not for venison chops, but as an advertising display.",
       "yt_trailer_code":"LsSM-cxp_ZQ",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/prancer_1989\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/prancer_1989\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/prancer_1989\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/prancer_1989\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/prancer_1989\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/50D66C669C36B127DC0E5C8256237E001392B3B3",
             "hash":"50D66C669C36B127DC0E5C8256237E001392B3B3",
             "quality":"720p",
             "type":"web",
             "seeds":115,
             "peers":75,
             "size":"910.53 MB",
             "size_bytes":954759905,
             "date_uploaded":"2019-11-03 02:30:35",
             "date_uploaded_unix":1572744635
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/48D01F611C6B6810152FF0FD4080340CBF960EA3",
             "hash":"48D01F611C6B6810152FF0FD4080340CBF960EA3",
             "quality":"1080p",
             "type":"web",
             "seeds":189,
             "peers":82,
             "size":"1.61 GB",
             "size_bytes":1728724337,
             "date_uploaded":"2019-11-03 04:36:23",
             "date_uploaded_unix":1572752183
          }
       ],
       "date_uploaded":"2019-11-03 02:30:35",
       "date_uploaded_unix":1572744635
    },
    { 
       "id":14123,
       "url":"https:\/\/yts.lt\/movie\/chasing-grace-2015",
       "imdb_code":"tt3475540",
       "title":"Chasing Grace",
       "title_english":"Chasing Grace",
       "title_long":"Chasing Grace (2015)",
       "slug":"chasing-grace-2015",
       "year":2015,
       "rating":4.7,
       "runtime":96,
       "genres":[ 
          "Drama"
       ],
       "summary":"A tragedy sets into motion a complex betrayal between two brothers, while exposing a secret no one wants to face.",
       "description_full":"A tragedy sets into motion a complex betrayal between two brothers, while exposing a secret no one wants to face.",
       "synopsis":"A tragedy sets into motion a complex betrayal between two brothers, while exposing a secret no one wants to face.",
       "yt_trailer_code":"",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/chasing_grace_2015\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/chasing_grace_2015\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/chasing_grace_2015\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/chasing_grace_2015\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/chasing_grace_2015\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/BBDB39474B2F23565AE250DFBE577C7EEB369261",
             "hash":"BBDB39474B2F23565AE250DFBE577C7EEB369261",
             "quality":"720p",
             "type":"web",
             "seeds":29,
             "peers":18,
             "size":"857.87 MB",
             "size_bytes":899541893,
             "date_uploaded":"2019-11-03 02:13:02",
             "date_uploaded_unix":1572743582
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/7DBE7939A3E32DE4FC84DA976746F494295277DE",
             "hash":"7DBE7939A3E32DE4FC84DA976746F494295277DE",
             "quality":"1080p",
             "type":"web",
             "seeds":61,
             "peers":18,
             "size":"1.51 GB",
             "size_bytes":1621350154,
             "date_uploaded":"2019-11-03 03:37:45",
             "date_uploaded_unix":1572748665
          }
       ],
       "date_uploaded":"2019-11-03 02:13:02",
       "date_uploaded_unix":1572743582
    },
    { 
       "id":14122,
       "url":"https:\/\/yts.lt\/movie\/must-love-dogs-2005",
       "imdb_code":"tt0417001",
       "title":"Must Love Dogs",
       "title_english":"Must Love Dogs",
       "title_long":"Must Love Dogs (2005)",
       "slug":"must-love-dogs-2005",
       "year":2005,
       "rating":5.9,
       "runtime":98,
       "genres":[ 
          "Comedy",
          "Romance"
       ],
       "summary":"Preschool teacher Sarah Nolan, divorced for eight months, is still grieving the end of her marriage. Although she didn't see it as being perfect, she probably would have stuck it out as what she saw as the \"for better or worse\" obligation of the wedding vows, that is if her ex-husband, Kevin, didn't end it for what ended up being leaving her for a younger woman. She is urged by her over-supportive family, comprised of her many siblings, their partners, and her widowed father, to get back into the dating scene, something she has been reluctant to do in not feeling ready. As such, her most proactive sister in the matter, Carol, sets her up on an Internet dating site. Within her less than prepared state, Sarah does go along with meeting men by the means offered to her. Beyond especially her female siblings, Sarah is given unique perspectives on the whole issue of dating and commitment by her father, Bill, who is exploring dating after losing who was the love of his life in Sarah's mother...",
       "description_full":"Preschool teacher Sarah Nolan, divorced for eight months, is still grieving the end of her marriage. Although she didn't see it as being perfect, she probably would have stuck it out as what she saw as the \"for better or worse\" obligation of the wedding vows, that is if her ex-husband, Kevin, didn't end it for what ended up being leaving her for a younger woman. She is urged by her over-supportive family, comprised of her many siblings, their partners, and her widowed father, to get back into the dating scene, something she has been reluctant to do in not feeling ready. As such, her most proactive sister in the matter, Carol, sets her up on an Internet dating site. Within her less than prepared state, Sarah does go along with meeting men by the means offered to her. Beyond especially her female siblings, Sarah is given unique perspectives on the whole issue of dating and commitment by her father, Bill, who is exploring dating after losing who was the love of his life in Sarah's mother...",
       "synopsis":"Preschool teacher Sarah Nolan, divorced for eight months, is still grieving the end of her marriage. Although she didn't see it as being perfect, she probably would have stuck it out as what she saw as the \"for better or worse\" obligation of the wedding vows, that is if her ex-husband, Kevin, didn't end it for what ended up being leaving her for a younger woman. She is urged by her over-supportive family, comprised of her many siblings, their partners, and her widowed father, to get back into the dating scene, something she has been reluctant to do in not feeling ready. As such, her most proactive sister in the matter, Carol, sets her up on an Internet dating site. Within her less than prepared state, Sarah does go along with meeting men by the means offered to her. Beyond especially her female siblings, Sarah is given unique perspectives on the whole issue of dating and commitment by her father, Bill, who is exploring dating after losing who was the love of his life in Sarah's mother...",
       "yt_trailer_code":"ASWRj-8da9o",
       "language":"English",
       "mpa_rating":"PG-13",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/must_love_dogs_2005\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/must_love_dogs_2005\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/must_love_dogs_2005\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/must_love_dogs_2005\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/must_love_dogs_2005\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/BAF483457BDF7A39EF906384C71FAD4ADD930E62",
             "hash":"BAF483457BDF7A39EF906384C71FAD4ADD930E62",
             "quality":"720p",
             "type":"web",
             "seeds":183,
             "peers":60,
             "size":"857.46 MB",
             "size_bytes":899111977,
             "date_uploaded":"2019-11-02 23:58:33",
             "date_uploaded_unix":1572735513
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/1A6C60DDEF94D1625493632C3E28ED7CC4E78751",
             "hash":"1A6C60DDEF94D1625493632C3E28ED7CC4E78751",
             "quality":"1080p",
             "type":"web",
             "seeds":215,
             "peers":105,
             "size":"1.52 GB",
             "size_bytes":1632087572,
             "date_uploaded":"2019-11-03 01:26:26",
             "date_uploaded_unix":1572740786
          }
       ],
       "date_uploaded":"2019-11-02 23:58:33",
       "date_uploaded_unix":1572735513
    },
    { 
       "id":14121,
       "url":"https:\/\/yts.lt\/movie\/tigers-are-not-afraid-2017",
       "imdb_code":"tt4823434",
       "title":"Tigers Are Not Afraid",
       "title_english":"Tigers Are Not Afraid",
       "title_long":"Tigers Are Not Afraid (2017)",
       "slug":"tigers-are-not-afraid-2017",
       "year":2017,
       "rating":7.1,
       "runtime":83,
       "genres":[ 
          "Fantasy",
          "Horror",
          "Mystery"
       ],
       "summary":"Estrella is 10 years old and has 3 wishes: The first one, that her missing mother comes back and it happens. Her mother returns but she is dead and follows Estrella everywhere. Petrified, Estrella tries to escape from her by joining a gang orphaned by violence. Soon she realizes that dead are never left behind and when you are in the middle of brutality and violence, wishes never come true the way you want them to be.",
       "description_full":"Estrella is 10 years old and has 3 wishes: The first one, that her missing mother comes back and it happens. Her mother returns but she is dead and follows Estrella everywhere. Petrified, Estrella tries to escape from her by joining a gang orphaned by violence. Soon she realizes that dead are never left behind and when you are in the middle of brutality and violence, wishes never come true the way you want them to be.",
       "synopsis":"Estrella is 10 years old and has 3 wishes: The first one, that her missing mother comes back and it happens. Her mother returns but she is dead and follows Estrella everywhere. Petrified, Estrella tries to escape from her by joining a gang orphaned by violence. Soon she realizes that dead are never left behind and when you are in the middle of brutality and violence, wishes never come true the way you want them to be.",
       "yt_trailer_code":"LPhKZZQpzec",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/tigers_are_not_afraid_2017\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/tigers_are_not_afraid_2017\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/tigers_are_not_afraid_2017\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/tigers_are_not_afraid_2017\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/tigers_are_not_afraid_2017\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/E27070C56A4AE77A3D74CF6BCE01C96877FE6EDD",
             "hash":"E27070C56A4AE77A3D74CF6BCE01C96877FE6EDD",
             "quality":"720p",
             "type":"web",
             "seeds":341,
             "peers":101,
             "size":"746.89 MB",
             "size_bytes":783170929,
             "date_uploaded":"2019-11-02 23:47:56",
             "date_uploaded_unix":1572734876
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/DF55139F642CBED277ABC2798274A424D7433450",
             "hash":"DF55139F642CBED277ABC2798274A424D7433450",
             "quality":"1080p",
             "type":"web",
             "seeds":422,
             "peers":145,
             "size":"1.31 GB",
             "size_bytes":1406601789,
             "date_uploaded":"2019-11-03 01:22:26",
             "date_uploaded_unix":1572740546
          }
       ],
       "date_uploaded":"2019-11-02 23:47:56",
       "date_uploaded_unix":1572734876
    },
    { 
       "id":14120,
       "url":"https:\/\/yts.lt\/movie\/learning-to-drive-2014",
       "imdb_code":"tt3062976",
       "title":"Learning to Drive",
       "title_english":"Learning to Drive",
       "title_long":"Learning to Drive (2014)",
       "slug":"learning-to-drive-2014",
       "year":2014,
       "rating":6.4,
       "runtime":90,
       "genres":[ 
          "Comedy",
          "Drama",
          "Romance"
       ],
       "summary":"Wendy (Patrician Clarkson), a self-absorbed New York book critic, is shocked to reality by the sudden end of her marriage. Always dependent on her husband for driving, she must now learn to take the wheel on her own. Her instructor Darwan (Ben Kingsley) is a Sikh Indian who watches with alarm as his pupil falls apart at the seams. He himself is contemplating an arranged marriage with a woman he has never met. As these two lives intersect, both will change in unpredictable ways.",
       "description_full":"Wendy (Patrician Clarkson), a self-absorbed New York book critic, is shocked to reality by the sudden end of her marriage. Always dependent on her husband for driving, she must now learn to take the wheel on her own. Her instructor Darwan (Ben Kingsley) is a Sikh Indian who watches with alarm as his pupil falls apart at the seams. He himself is contemplating an arranged marriage with a woman he has never met. As these two lives intersect, both will change in unpredictable ways.",
       "synopsis":"Wendy (Patrician Clarkson), a self-absorbed New York book critic, is shocked to reality by the sudden end of her marriage. Always dependent on her husband for driving, she must now learn to take the wheel on her own. Her instructor Darwan (Ben Kingsley) is a Sikh Indian who watches with alarm as his pupil falls apart at the seams. He himself is contemplating an arranged marriage with a woman he has never met. As these two lives intersect, both will change in unpredictable ways.",
       "yt_trailer_code":"IThfFYmEGEs",
       "language":"English",
       "mpa_rating":"R",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/learning_to_drive_2014\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/learning_to_drive_2014\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/learning_to_drive_2014\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/learning_to_drive_2014\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/learning_to_drive_2014\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/AE8390956397D59D00BC20CBD65B1A09F164342D",
             "hash":"AE8390956397D59D00BC20CBD65B1A09F164342D",
             "quality":"720p",
             "type":"bluray",
             "seeds":167,
             "peers":35,
             "size":"788.19 MB",
             "size_bytes":826477117,
             "date_uploaded":"2019-11-02 16:47:09",
             "date_uploaded_unix":1572709629
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/26D03BBE04AEA128C3D08941410102937C84E14F",
             "hash":"26D03BBE04AEA128C3D08941410102937C84E14F",
             "quality":"1080p",
             "type":"bluray",
             "seeds":159,
             "peers":64,
             "size":"1.4 GB",
             "size_bytes":1503238554,
             "date_uploaded":"2019-11-02 19:00:37",
             "date_uploaded_unix":1572717637
          }
       ],
       "date_uploaded":"2019-11-02 16:47:09",
       "date_uploaded_unix":1572709629
    },
    { 
       "id":14119,
       "url":"https:\/\/yts.lt\/movie\/nola-2003",
       "imdb_code":"tt0317950",
       "title":"Nola",
       "title_english":"Nola",
       "title_long":"Nola (2003)",
       "slug":"nola-2003",
       "year":2003,
       "rating":5.3,
       "runtime":0,
       "genres":[ 
          "Comedy",
          "Romance"
       ],
       "summary":"An urban fairy tale-romantic comedy, in which Nola, an aspiring songwriter, leaves an abusive Kansas home and journeys to New York to find her biological father. Once there, she finds more than she expected.",
       "description_full":"An urban fairy tale-romantic comedy, in which Nola, an aspiring songwriter, leaves an abusive Kansas home and journeys to New York to find her biological father. Once there, she finds more than she expected.",
       "synopsis":"An urban fairy tale-romantic comedy, in which Nola, an aspiring songwriter, leaves an abusive Kansas home and journeys to New York to find her biological father. Once there, she finds more than she expected.",
       "yt_trailer_code":"",
       "language":"English",
       "mpa_rating":"R",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/nola_2003\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/nola_2003\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/nola_2003\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/nola_2003\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/nola_2003\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/A7DEDC707A1213BD28DCC76049C7A437085EA2D3",
             "hash":"A7DEDC707A1213BD28DCC76049C7A437085EA2D3",
             "quality":"720p",
             "type":"web",
             "seeds":81,
             "peers":31,
             "size":"851.48 MB",
             "size_bytes":892841492,
             "date_uploaded":"2019-11-02 19:14:39",
             "date_uploaded_unix":1572718479
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/541322CAE453DAC5A69A2447AEB5B20595270286",
             "hash":"541322CAE453DAC5A69A2447AEB5B20595270286",
             "quality":"1080p",
             "type":"web",
             "seeds":80,
             "peers":27,
             "size":"1.52 GB",
             "size_bytes":1632087572,
             "date_uploaded":"2019-11-02 20:53:40",
             "date_uploaded_unix":1572724420
          }
       ],
       "date_uploaded":"2019-11-02 19:14:39",
       "date_uploaded_unix":1572718479
    },
    { 
       "id":14118,
       "url":"https:\/\/yts.lt\/movie\/shiraz-1928",
       "imdb_code":"tt0019374",
       "title":"Shiraz",
       "title_english":"Shiraz",
       "title_long":"Shiraz (1928)",
       "slug":"shiraz-1928",
       "year":1928,
       "rating":6.9,
       "runtime":97,
       "genres":[ 
          "Drama",
          "History",
          "Romance"
       ],
       "summary":"A historical romance set in the Mughal Empire. Selima (Enakshi) is a princess-foundling raised by a potter and loved by her brother, Shiraz (Rai). She is abducted and sold as a slave to Prince Khurram, later Emperor Shah Jehan (Roy), who falls for her, to the chagrin of the wily Dalia (Seeta Devi). When Selima is caught is Shiraz, the young man is condemned to be trampled to death by an elephant. A pendant reveals Selima's royal status and she saves her brother, marries the prince and becomes Empress Mumtaz Mahal while Dalia is banned for her machinations against Selima. When Selima dies (1629), the emperor builds her a monument to the design of the now old and blind Shiraz, the Taj Mahal. The film contains a number of passionate kissing scenes.",
       "description_full":"A historical romance set in the Mughal Empire. Selima (Enakshi) is a princess-foundling raised by a potter and loved by her brother, Shiraz (Rai). She is abducted and sold as a slave to Prince Khurram, later Emperor Shah Jehan (Roy), who falls for her, to the chagrin of the wily Dalia (Seeta Devi). When Selima is caught is Shiraz, the young man is condemned to be trampled to death by an elephant. A pendant reveals Selima's royal status and she saves her brother, marries the prince and becomes Empress Mumtaz Mahal while Dalia is banned for her machinations against Selima. When Selima dies (1629), the emperor builds her a monument to the design of the now old and blind Shiraz, the Taj Mahal. The film contains a number of passionate kissing scenes.",
       "synopsis":"A historical romance set in the Mughal Empire. Selima (Enakshi) is a princess-foundling raised by a potter and loved by her brother, Shiraz (Rai). She is abducted and sold as a slave to Prince Khurram, later Emperor Shah Jehan (Roy), who falls for her, to the chagrin of the wily Dalia (Seeta Devi). When Selima is caught is Shiraz, the young man is condemned to be trampled to death by an elephant. A pendant reveals Selima's royal status and she saves her brother, marries the prince and becomes Empress Mumtaz Mahal while Dalia is banned for her machinations against Selima. When Selima dies (1629), the emperor builds her a monument to the design of the now old and blind Shiraz, the Taj Mahal. The film contains a number of passionate kissing scenes.",
       "yt_trailer_code":"Plzfn64AR8E",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/shiraz_1928\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/shiraz_1928\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/shiraz_1928\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/shiraz_1928\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/shiraz_1928\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/DA843D50CFC52E9968EA93B99FDEA914DE5071EB",
             "hash":"DA843D50CFC52E9968EA93B99FDEA914DE5071EB",
             "quality":"720p",
             "type":"bluray",
             "seeds":71,
             "peers":24,
             "size":"932.56 MB",
             "size_bytes":977860035,
             "date_uploaded":"2019-11-02 16:53:29",
             "date_uploaded_unix":1572710009
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/C230384CD9AB52ECA88CF30132D523E1BA0A75AF",
             "hash":"C230384CD9AB52ECA88CF30132D523E1BA0A75AF",
             "quality":"1080p",
             "type":"bluray",
             "seeds":80,
             "peers":28,
             "size":"1.65 GB",
             "size_bytes":1771674010,
             "date_uploaded":"2019-11-02 18:21:42",
             "date_uploaded_unix":1572715302
          }
       ],
       "date_uploaded":"2019-11-02 16:53:29",
       "date_uploaded_unix":1572710009
    },
    { 
       "id":14117,
       "url":"https:\/\/yts.lt\/movie\/paradise-hills-2019",
       "imdb_code":"tt6127004",
       "title":"Paradise Hills",
       "title_english":"Paradise Hills",
       "title_long":"Paradise Hills (2019)",
       "slug":"paradise-hills-2019",
       "year":2019,
       "rating":6.3,
       "runtime":95,
       "genres":[ 
          "Fantasy",
          "Sci-Fi",
          "Thriller"
       ],
       "summary":"In an undetermined future, society has divided in two types: upper-class or \"superiors\", and the rest of the world, mid and lower-class, named \"inferiors\". Uma is a superior teen girl who reluctant to marry with another superior named Son to be fall in love of an inferior named Markus, her mother sends her to Paradise Hills, a school for young ladies to reform rebel girls located in a remote island in the middle of the ocean. Waking up in Paradise not knowing how she arrived there, in the island she meets another students of the school: Amarna, a world pop star who was sent after she decided sing her own songs against the will of her parents and the music company that produces her albums; Chloe, an over-weight girl which parents want to turn her in a perfect woman, thin and complaint; and Yu, an inferior that after the loss of her parents was sent with her superiors aunt and uncle, who wants to make perfect and superior as them. At the same time that Uma meets the eccentric and ...",
       "description_full":"In an undetermined future, society has divided in two types: upper-class or \"superiors\", and the rest of the world, mid and lower-class, named \"inferiors\". Uma is a superior teen girl who reluctant to marry with another superior named Son to be fall in love of an inferior named Markus, her mother sends her to Paradise Hills, a school for young ladies to reform rebel girls located in a remote island in the middle of the ocean. Waking up in Paradise not knowing how she arrived there, in the island she meets another students of the school: Amarna, a world pop star who was sent after she decided sing her own songs against the will of her parents and the music company that produces her albums; Chloe, an over-weight girl which parents want to turn her in a perfect woman, thin and complaint; and Yu, an inferior that after the loss of her parents was sent with her superiors aunt and uncle, who wants to make perfect and superior as them. At the same time that Uma meets the eccentric and ...",
       "synopsis":"In an undetermined future, society has divided in two types: upper-class or \"superiors\", and the rest of the world, mid and lower-class, named \"inferiors\". Uma is a superior teen girl who reluctant to marry with another superior named Son to be fall in love of an inferior named Markus, her mother sends her to Paradise Hills, a school for young ladies to reform rebel girls located in a remote island in the middle of the ocean. Waking up in Paradise not knowing how she arrived there, in the island she meets another students of the school: Amarna, a world pop star who was sent after she decided sing her own songs against the will of her parents and the music company that produces her albums; Chloe, an over-weight girl which parents want to turn her in a perfect woman, thin and complaint; and Yu, an inferior that after the loss of her parents was sent with her superiors aunt and uncle, who wants to make perfect and superior as them. At the same time that Uma meets the eccentric and ...",
       "yt_trailer_code":"qUVrH4BI-Cw",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/paradise_hills_2019\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/paradise_hills_2019\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/paradise_hills_2019\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/paradise_hills_2019\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/paradise_hills_2019\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/13ED009EB67274C5789BE269EBA266C7979BEDE3",
             "hash":"13ED009EB67274C5789BE269EBA266C7979BEDE3",
             "quality":"720p",
             "type":"web",
             "seeds":862,
             "peers":316,
             "size":"846.95 MB",
             "size_bytes":888091443,
             "date_uploaded":"2019-11-02 14:32:29",
             "date_uploaded_unix":1572701549
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/186EC8E4F4483D591CCF61F11B0BA1237DB99E52",
             "hash":"186EC8E4F4483D591CCF61F11B0BA1237DB99E52",
             "quality":"1080p",
             "type":"web",
             "seeds":967,
             "peers":372,
             "size":"1.49 GB",
             "size_bytes":1599875318,
             "date_uploaded":"2019-11-02 16:07:09",
             "date_uploaded_unix":1572707229
          }
       ],
       "date_uploaded":"2019-11-02 14:32:29",
       "date_uploaded_unix":1572701549
    },
    { 
       "id":14116,
       "url":"https:\/\/yts.lt\/movie\/mistrust-2018",
       "imdb_code":"tt4103470",
       "title":"Mistrust",
       "title_english":"Mistrust",
       "title_long":"Mistrust (2018)",
       "slug":"mistrust-2018",
       "year":2018,
       "rating":5.9,
       "runtime":90,
       "genres":[ 
          "Drama",
          "Romance"
       ],
       "summary":"Happy, beautiful and independent, Veronica enjoys being a mistress. No commitment, no strings and she never has to be vulnerable. She has carefully laid every brick in the walls of the fortress surrounding her heart. She's safe and having a great time. However, there is one person who knew her heart before those walls were erected, her best friend Brandon, who has stood by her for too many years to count. And while Veronica has tried to keep her feelings at bay, he is the one who holds the key that opens her Pandora's box of emotions.",
       "description_full":"Happy, beautiful and independent, Veronica enjoys being a mistress. No commitment, no strings and she never has to be vulnerable. She has carefully laid every brick in the walls of the fortress surrounding her heart. She's safe and having a great time. However, there is one person who knew her heart before those walls were erected, her best friend Brandon, who has stood by her for too many years to count. And while Veronica has tried to keep her feelings at bay, he is the one who holds the key that opens her Pandora's box of emotions.",
       "synopsis":"Happy, beautiful and independent, Veronica enjoys being a mistress. No commitment, no strings and she never has to be vulnerable. She has carefully laid every brick in the walls of the fortress surrounding her heart. She's safe and having a great time. However, there is one person who knew her heart before those walls were erected, her best friend Brandon, who has stood by her for too many years to count. And while Veronica has tried to keep her feelings at bay, he is the one who holds the key that opens her Pandora's box of emotions.",
       "yt_trailer_code":"jmdw7KebSeg",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/mistrust_2018\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/mistrust_2018\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/mistrust_2018\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/mistrust_2018\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/mistrust_2018\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/936688FD1C70BFB969015D49C672B7649125E1A8",
             "hash":"936688FD1C70BFB969015D49C672B7649125E1A8",
             "quality":"720p",
             "type":"web",
             "seeds":143,
             "peers":51,
             "size":"788.6 MB",
             "size_bytes":826907034,
             "date_uploaded":"2019-11-02 13:35:11",
             "date_uploaded_unix":1572698111
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/CD380DF4441EE5F7BD92B0C914EB9616CFBCF8B0",
             "hash":"CD380DF4441EE5F7BD92B0C914EB9616CFBCF8B0",
             "quality":"1080p",
             "type":"web",
             "seeds":120,
             "peers":35,
             "size":"1.4 GB",
             "size_bytes":1503238554,
             "date_uploaded":"2019-11-02 15:35:30",
             "date_uploaded_unix":1572705330
          }
       ],
       "date_uploaded":"2019-11-02 13:35:11",
       "date_uploaded_unix":1572698111
    },
    { 
       "id":14115,
       "url":"https:\/\/yts.lt\/movie\/strength-in-numbers-2012",
       "imdb_code":"tt5001094",
       "title":"Strength in Numbers",
       "title_english":"Strength in Numbers",
       "title_long":"Strength in Numbers (2012)",
       "slug":"strength-in-numbers-2012",
       "year":2012,
       "rating":8,
       "runtime":52,
       "genres":[ 
          "Documentary"
       ],
       "summary":"Strength in Numbers is a rally call to connect all mountain bikers, regardless of location or language or discipline. Tire to ground, foot to pedal, hand to bar - communities drawn together by trails of dirt.",
       "description_full":"Strength in Numbers is a rally call to connect all mountain bikers, regardless of location or language or discipline. Tire to ground, foot to pedal, hand to bar - communities drawn together by trails of dirt.",
       "synopsis":"Strength in Numbers is a rally call to connect all mountain bikers, regardless of location or language or discipline. Tire to ground, foot to pedal, hand to bar - communities drawn together by trails of dirt.",
       "yt_trailer_code":"xORYfLLZck8",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/strength_in_numbers_2012\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/strength_in_numbers_2012\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/strength_in_numbers_2012\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/strength_in_numbers_2012\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/strength_in_numbers_2012\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/41B3CBC208AD86CF85A64F7263AC74575F3AE821",
             "hash":"41B3CBC208AD86CF85A64F7263AC74575F3AE821",
             "quality":"720p",
             "type":"bluray",
             "seeds":43,
             "peers":7,
             "size":"472.47 MB",
             "size_bytes":495420703,
             "date_uploaded":"2019-11-02 02:13:05",
             "date_uploaded_unix":1572657185
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/4648B3C152DC1461D555C5B003A26927A8D59BC6",
             "hash":"4648B3C152DC1461D555C5B003A26927A8D59BC6",
             "quality":"1080p",
             "type":"bluray",
             "seeds":75,
             "peers":14,
             "size":"852.9 MB",
             "size_bytes":894330470,
             "date_uploaded":"2019-11-02 03:11:03",
             "date_uploaded_unix":1572660663
          }
       ],
       "date_uploaded":"2019-11-02 02:13:05",
       "date_uploaded_unix":1572657185
    },
    { 
       "id":14114,
       "url":"https:\/\/yts.lt\/movie\/a-guide-to-second-date-sex-2019",
       "imdb_code":"tt7439748",
       "title":"A Guide to Second Date Sex",
       "title_english":"A Guide to Second Date Sex",
       "title_long":"A Guide to Second Date Sex (2019)",
       "slug":"a-guide-to-second-date-sex-2019",
       "year":2019,
       "rating":2.9,
       "runtime":0,
       "genres":[ 
          "Comedy",
          "Romance"
       ],
       "summary":"Laura and Ryan are perfect for each other: they both love Meryl Streep, have been totally destroyed by previous relationships, and they have no idea what they are supposed to do tonight. They also both know that they'll have to pretend to be completely different to how they've ever been previously, in the hope of getting it right this time. How bad can a second date really go and what is there to lose? Ryan and Laura are about to find out.",
       "description_full":"Laura and Ryan are perfect for each other: they both love Meryl Streep, have been totally destroyed by previous relationships, and they have no idea what they are supposed to do tonight. They also both know that they'll have to pretend to be completely different to how they've ever been previously, in the hope of getting it right this time. How bad can a second date really go and what is there to lose? Ryan and Laura are about to find out.",
       "synopsis":"Laura and Ryan are perfect for each other: they both love Meryl Streep, have been totally destroyed by previous relationships, and they have no idea what they are supposed to do tonight. They also both know that they'll have to pretend to be completely different to how they've ever been previously, in the hope of getting it right this time. How bad can a second date really go and what is there to lose? Ryan and Laura are about to find out.",
       "yt_trailer_code":"",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/a_guide_to_second_date_sex_2019\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/a_guide_to_second_date_sex_2019\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/a_guide_to_second_date_sex_2019\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/a_guide_to_second_date_sex_2019\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/a_guide_to_second_date_sex_2019\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/6EFDEE74BA183B65C1AC3AB9E1D22B4523A447C2",
             "hash":"6EFDEE74BA183B65C1AC3AB9E1D22B4523A447C2",
             "quality":"720p",
             "type":"web",
             "seeds":342,
             "peers":106,
             "size":"712.3 MB",
             "size_bytes":746900685,
             "date_uploaded":"2019-11-02 06:31:38",
             "date_uploaded_unix":1572672698
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/A0FBF6DC5CD4F7982FBDA0C3440D819396270B90",
             "hash":"A0FBF6DC5CD4F7982FBDA0C3440D819396270B90",
             "quality":"1080p",
             "type":"web",
             "seeds":215,
             "peers":77,
             "size":"1.26 GB",
             "size_bytes":1352914698,
             "date_uploaded":"2019-11-02 08:02:01",
             "date_uploaded_unix":1572678121
          }
       ],
       "date_uploaded":"2019-11-02 06:31:38",
       "date_uploaded_unix":1572672698
    },
    { 
       "id":14113,
       "url":"https:\/\/yts.lt\/movie\/a-bucket-of-blood-1959",
       "imdb_code":"tt0052655",
       "title":"A Bucket of Blood",
       "title_english":"A Bucket of Blood",
       "title_long":"A Bucket of Blood (1959)",
       "slug":"a-bucket-of-blood-1959",
       "year":1959,
       "rating":6.7,
       "runtime":66,
       "genres":[ 
          "Comedy",
          "Crime",
          "Horror"
       ],
       "summary":"Walter Paisley, nerdy busboy at a Bohemian caf\u00e9, is jealous of the talent (and popularity) of its various artistic regulars. But after accidentally killing his landlady's cat and covering the body in plaster to hide the evidence, he is acclaimed as a brilliant sculptor - but his new-found friends want to see more of his work. Lacking any artistic talent whatsoever, Walter has to resort to similar methods to produce new work, and soon people start mysteriously disappearing...",
       "description_full":"Walter Paisley, nerdy busboy at a Bohemian caf\u00e9, is jealous of the talent (and popularity) of its various artistic regulars. But after accidentally killing his landlady's cat and covering the body in plaster to hide the evidence, he is acclaimed as a brilliant sculptor - but his new-found friends want to see more of his work. Lacking any artistic talent whatsoever, Walter has to resort to similar methods to produce new work, and soon people start mysteriously disappearing...",
       "synopsis":"Walter Paisley, nerdy busboy at a Bohemian caf\u00e9, is jealous of the talent (and popularity) of its various artistic regulars. But after accidentally killing his landlady's cat and covering the body in plaster to hide the evidence, he is acclaimed as a brilliant sculptor - but his new-found friends want to see more of his work. Lacking any artistic talent whatsoever, Walter has to resort to similar methods to produce new work, and soon people start mysteriously disappearing...",
       "yt_trailer_code":"EdqECygfvtQ",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/a_bucket_of_blood_1959\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/a_bucket_of_blood_1959\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/a_bucket_of_blood_1959\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/a_bucket_of_blood_1959\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/a_bucket_of_blood_1959\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/969F4E36C9B219C28E28B7825729CB7282A4831B",
             "hash":"969F4E36C9B219C28E28B7825729CB7282A4831B",
             "quality":"720p",
             "type":"bluray",
             "seeds":34,
             "peers":7,
             "size":"569.44 MB",
             "size_bytes":597101117,
             "date_uploaded":"2019-11-02 04:10:37",
             "date_uploaded_unix":1572664237
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/1976EE35E0A7BD07C37BE7C99A4CB0CAFF717AF7",
             "hash":"1976EE35E0A7BD07C37BE7C99A4CB0CAFF717AF7",
             "quality":"1080p",
             "type":"bluray",
             "seeds":71,
             "peers":12,
             "size":"1.01 GB",
             "size_bytes":1084479242,
             "date_uploaded":"2019-11-02 05:44:08",
             "date_uploaded_unix":1572669848
          }
       ],
       "date_uploaded":"2019-11-02 04:10:37",
       "date_uploaded_unix":1572664237
    },
    { 
       "id":14112,
       "url":"https:\/\/yts.lt\/movie\/death-warmed-up-1984",
       "imdb_code":"tt0089002",
       "title":"Death Warmed Up",
       "title_english":"Death Warmed Up",
       "title_long":"Death Warmed Up (1984)",
       "slug":"death-warmed-up-1984",
       "year":1984,
       "rating":4.4,
       "runtime":0,
       "genres":[ 
          "Horror",
          "Sci-Fi"
       ],
       "summary":"A kid is hypnotized by a scientist to kill his parents and ends in a mental institution. As a grown up he returns to seek revenge over the scientist.",
       "description_full":"A kid is hypnotized by a scientist to kill his parents and ends in a mental institution. As a grown up he returns to seek revenge over the scientist.",
       "synopsis":"A kid is hypnotized by a scientist to kill his parents and ends in a mental institution. As a grown up he returns to seek revenge over the scientist.",
       "yt_trailer_code":"ApMXRIq54Vc",
       "language":"English",
       "mpa_rating":"",
       "background_image":"https:\/\/yts.lt\/assets\/images\/movies\/death_warmed_up_1984\/background.jpg",
       "background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/death_warmed_up_1984\/background.jpg",
       "small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/death_warmed_up_1984\/small-cover.jpg",
       "medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/death_warmed_up_1984\/medium-cover.jpg",
       "large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/death_warmed_up_1984\/large-cover.jpg",
       "state":"ok",
       "torrents":[ 
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/9209AF56DC99D5334B51AFEFF23676A031934F64",
             "hash":"9209AF56DC99D5334B51AFEFF23676A031934F64",
             "quality":"720p",
             "type":"bluray",
             "seeds":64,
             "peers":16,
             "size":"708.15 MB",
             "size_bytes":742549094,
             "date_uploaded":"2019-11-02 01:23:35",
             "date_uploaded_unix":1572654215
          },
          { 
             "url":"https:\/\/yts.lt\/torrent\/download\/EEEBAF31094BBE0B710C9F8B6000EA7F7B58970C",
             "hash":"EEEBAF31094BBE0B710C9F8B6000EA7F7B58970C",
             "quality":"1080p",
             "type":"bluray",
             "seeds":61,
             "peers":17,
             "size":"1.24 GB",
             "size_bytes":1331439862,
             "date_uploaded":"2019-11-02 03:20:52",
             "date_uploaded_unix":1572661252
          }
       ],
       "date_uploaded":"2019-11-02 01:23:35",
       "date_uploaded_unix":1572654215
    }
 ]